name: thesis-tf
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - pip:
      - tensorflow==2.15.*
