[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B"]
ignore = ["E203","E266","E501"]

[tool.ruff.isort]
known-first-party = ["thesis_llm"]
